### ISSUE TITLE
AttributeError: 'list' object has no attribute 'clear'

### ISSUE THREAD

**Issue by coler-j** [edoburu/sphinxcontrib-django#6]
Getting this error when trying to build html:

`Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\sphinx\cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "C:\Python27\lib\site-packages\sphinx\application.py", line 331, in build
    self.builder.build_update()
  File "C:\Python27\lib\site-packages\sphinx\builders\__init__.py", line 333, in build_update
    'out of date' % len(to_build))
  File "C:\Python27\lib\site-packages\sphinx\builders\__init__.py", line 346, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "C:\Python27\lib\site-packages\sphinx\environment\__init__.py", line 565, in update
    self._read_serial(docnames, self.app)
  File "C:\Python27\lib\site-packages\sphinx\environment\__init__.py", line 584, in _read_serial
    self.read_doc(docname, app)
  File "C:\Python27\lib\site-packages\sphinx\environment\__init__.py", line 659, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "C:\Python27\lib\site-packages\sphinx\io.py", line 294, in read_doc
    pub.publish()
  File "C:\Python27\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "C:\Python27\lib\site-packages\docutils\readers\__init__.py", line 72, in read
    self.parse()
  File "C:\Python27\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\Python27\lib\site-packages\sphinx\parsers.py", line 86, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 171, in run
    input_source=document['source'])
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2988, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\directive.py", line 134, in run
    documenter.generate(more_content=self.content)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 793, in generate
    self.document_members(all_members)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 714, in document_members
    check_module=members_check_module and not isattr)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1203, in generate
    all_members=all_members)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 793, in generate
    self.document_members(all_members)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1192, in document_members
    ModuleLevelDocumenter.document_members(self, all_members)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 714, in document_members
    check_module=members_check_module and not isattr)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 790, in generate
    self.add_content(more_content)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1391, in add_content
    ClassLevelDocumenter.add_content(self, more_content, no_docstring)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 525, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 497, in process_doc
    self.options, docstringlines)
  File "C:\Python27\lib\site-packages\sphinx\application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "C:\Python27\lib\site-packages\sphinx\events.py", line 79, in emit
    results.append(callback(*args))
  File "C:\Python27\lib\site-packages\sphinxcontrib_django\docstrings.py", line 105, in improve_model_docstring
    _improve_attribute_docs(obj, name, lines)
  File "C:\Python27\lib\site-packages\sphinxcontrib_django\docstrings.py", line 212, in _improve_attribute_docs
    lines.clear()
AttributeError: 'list' object has no attribute 'clear'`

**Comment by coler-j** [comment]
Package says that it works with py2.7 ? But clear() is a py3.x method.

**Comment by coler-j** [comment]
To get it to work for py2.7 I replaced `line.clear()` with `del lines[:]`

**Comment by vdboor** [comment]
Thanks, I've fixed this in v0.3.1 / 8099c44132883fd475a6cccd79046cde37aaa86f
